# Generated by Django 6.1 on 2026-08-07 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='Categoría')),
                ('size', models.CharField(blank=True, default='', max_length=50, verbose_name='Talle')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de compra')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de venta')),
                ('status', models.CharField(choices=[('in_stock', 'En stock'), ('sold', 'Vendido'), ('reserved', 'Reservado'), ('returned', 'Devuelto')], default='in_stock', max_length=20, verbose_name='Estado')),
                ('purchase_date', models.DateField(verbose_name='Fecha de compra')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Fecha de venta')),
                ('buyer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Comprador')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='araceli/clothing/%Y/%m/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NailService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200, verbose_name='Cliente')),
                ('service_type', models.CharField(choices=[('esculpidas', 'Esculpidas'), ('semipermanente', 'Semipermanente'), ('kapping', 'Kapping'), ('soft_gel', 'Soft gel'), ('retoque', 'Retoque'), ('retirada', 'Retirada'), ('pies', 'Pies'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de servicio')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de insumos')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='araceli/nails/%Y/%m/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nail_services', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Servicio de uñas',
                'verbose_name_plural': 'Servicios de uñas',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
