# Generated by Django 5.2.1 on 2026-01-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=3, verbose_name='Moneda'),
        ),
    ]
