# Generated by Django 5.2.1 on 2026-01-19 23:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_bankaccount_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='used',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='currency',
            field=models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', help_text='Moneda en la que está expresado el límite de crédito', max_length=3, verbose_name='Moneda de la línea'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='used_pen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consumo en soles'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='used_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consumo en dólares'),
        ),
        migrations.AddField(
            model_name='expense',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finances.bankaccount', verbose_name='Cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=3, verbose_name='Moneda'),
        ),
    ]
