# Generated by Django 5.2.1 on 2026-01-21 02:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_creditcard_used_creditcard_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto')),
                ('category', models.CharField(choices=[('salary', 'Sueldo'), ('freelance', 'Freelance'), ('investment', 'Inversión'), ('gift', 'Regalo'), ('refund', 'Reembolso'), ('other', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('currency', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=3, verbose_name='Moneda')),
                ('date', models.DateField(verbose_name='Fecha del ingreso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='finances.bankaccount', verbose_name='Cuenta bancaria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
