# Generated by Django 5.2.1 on 2026-01-24 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('finances', '0006_fixedexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='categories.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='fixedexpense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_expenses', to='categories.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='categories.category', verbose_name='Categoría'),
        ),
    ]
