# Generated by Django 5.2.1 on 2026-01-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_fixedincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance'),
        ),
    ]
