# Generated by Django - Data migration to assign bank accounts to existing expenses

from django.db import migrations


def assign_bank_accounts_to_expenses(apps, schema_editor):
    """
    Asigna la cuenta bancaria correspondiente a cada gasto existente
    que no tenga tarjeta de crédito ni cuenta bancaria asignada.
    """
    Expense = apps.get_model('finances', 'Expense')
    BankAccount = apps.get_model('finances', 'BankAccount')

    # Obtener gastos sin cuenta bancaria y sin tarjeta de crédito
    expenses_to_update = Expense.objects.filter(
        bank_account__isnull=True,
        credit_card__isnull=True
    )

    updated_count = 0
    for expense in expenses_to_update:
        # Buscar cuenta bancaria del usuario con la misma moneda
        bank_account = BankAccount.objects.filter(
            user=expense.user,
            currency=expense.currency
        ).first()

        if bank_account:
            expense.bank_account = bank_account
            expense.save(update_fields=['bank_account'])
            updated_count += 1

    print(f"Migrated {updated_count} expenses to their corresponding bank accounts")


def reverse_migration(apps, schema_editor):
    """
    Revierte la migración quitando las cuentas bancarias asignadas.
    (No recomendado, solo para rollback de emergencia)
    """
    pass  # No hacemos nada para no perder datos


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_remove_balance_min_validator'),
    ]

    operations = [
        migrations.RunPython(
            assign_bank_accounts_to_expenses,
            reverse_migration
        ),
    ]
