# Generated by Django 6.0.1 on 2026-01-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_assign_bank_accounts_to_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='add_incomes',
            field=models.BooleanField(default=False, help_text='Si está activo, suma los ingresos al saldo', verbose_name='Sumar ingresos'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='subtract_expenses',
            field=models.BooleanField(default=True, help_text='Si está activo, resta los gastos del saldo', verbose_name='Restar gastos'),
        ),
    ]
