# Generated by Django 5.2.1 on 2026-01-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_creditcardpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance_updated_at',
            field=models.DateTimeField(blank=True, help_text='Si tiene valor, solo gastos/ingresos creados después de esta fecha afectan el saldo', null=True, verbose_name='Fecha de actualización del saldo'),
        ),
    ]
