# Generated by Django 6.0.1 on 2026-02-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_add_balance_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpense',
            name='last_processed_date',
            field=models.DateField(blank=True, help_text='Fecha del último mes en que se convirtió a gasto real', null=True, verbose_name='Última fecha procesada'),
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='last_processed_date',
            field=models.DateField(blank=True, help_text='Fecha del último mes en que se convirtió a ingreso real', null=True, verbose_name='Última fecha procesada'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='add_incomes',
            field=models.BooleanField(default=True, help_text='Si está activo, suma los ingresos al saldo', verbose_name='Sumar ingresos'),
        ),
    ]
