# Generated by Django 6.0.1 on 2026-02-01 16:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_change_add_incomes_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_from', models.DecimalField(decimal_places=2, help_text='Monto en la moneda de la cuenta origen', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto origen')),
                ('amount_to', models.DecimalField(decimal_places=2, help_text='Monto en la moneda de la cuenta destino', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto destino')),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='Tipo de cambio aplicado', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Tipo de cambio')),
                ('date', models.DateField(verbose_name='Fecha del cambio')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_out', to='finances.bankaccount', verbose_name='Cuenta origen')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_in', to='finances.bankaccount', verbose_name='Cuenta destino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchanges', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cambio de divisa',
                'verbose_name_plural': 'Cambios de divisa',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
