# Generated by Django 6.0.1 on 2026-01-18 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('career', 'Carrera'), ('health', 'Salud'), ('education', 'Educación'), ('finance', 'Finanzas'), ('personal', 'Personal'), ('relationships', 'Relaciones')], max_length=20, verbose_name='Categoría')),
                ('status', models.CharField(choices=[('not_started', 'Sin iniciar'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('paused', 'Pausado')], default='not_started', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('linked_finance_type', models.CharField(blank=True, choices=[('savings', 'Ahorro'), ('expense_limit', 'Límite de gasto')], max_length=20, null=True, verbose_name='Tipo de meta financiera')),
                ('linked_finance_target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Meta financiera')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor actual')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor objetivo')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='goals.objective', verbose_name='Objetivo')),
            ],
            options={
                'verbose_name': 'Resultado Clave',
                'verbose_name_plural': 'Resultados Clave',
                'ordering': ['created_at'],
            },
        ),
    ]
