# Generated by Django 5.2.1 on 2026-01-22 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresult',
            name='measurement_type',
            field=models.CharField(choices=[('numeric', 'Numérico'), ('currency', 'Monetario'), ('percentage', 'Porcentaje'), ('boolean', 'Sí/No'), ('milestone', 'Hitos')], default='numeric', max_length=20, verbose_name='Tipo de medición'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unidad'),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='goals.keyresult', verbose_name='Resultado Clave')),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
                'ordering': ['order'],
            },
        ),
    ]
